### ISSUE TITLE
use consistent line spacing

### ISSUE THREAD

**Issue by snotskie** [Tiny-Earth/DemoSite#16]
For example, a blank line is missing here: https://github.com/Tiny-Earth/DemoSite/blob/4e507465ae84787f1695f3432c9bf4cf18581e18/site/src/inclusive.md?plain=1#L12-L14

As well as here: https://github.com/Tiny-Earth/DemoSite/blob/4e507465ae84787f1695f3432c9bf4cf18581e18/site/src/inclusive.md?plain=1#L220-L221

And here there are too many spaces: https://github.com/Tiny-Earth/DemoSite/blob/4e507465ae84787f1695f3432c9bf4cf18581e18/site/src/intro.md?plain=1#L97-L100

There should be exactly one blank line above and below all:

- paragraphs
- lists
- headings (`##`, `###`, and `####`)
- admonitions (`!!!`)
- rules (`---`)

Also, all markdown files should end with exactly one blank line

**Comment by marzwick** [comment]
d93feb6
