### ISSUE TITLE
Remove extraneous * in <mark>s

### ISSUE THREAD

**Issue by snotskie** [Tiny-Earth/DemoSite#18]
Here: https://github.com/Tiny-Earth/DemoSite/blob/4e507465ae84787f1695f3432c9bf4cf18581e18/site/src/intro.md?plain=1#L42-L44

And here: https://github.com/Tiny-Earth/DemoSite/blob/4e507465ae84787f1695f3432c9bf4cf18581e18/site/src/intro.md?plain=1#L112-L114

And here: https://github.com/Tiny-Earth/DemoSite/blob/4e507465ae84787f1695f3432c9bf4cf18581e18/site/src/intro.md?plain=1#L122-L124

Remove the extra `*`, since that is a part of Markdown syntax. Once we are in the `@raw html` environment, we can stick to pure `<mark>` tags, which can then be styled separately in `style.css`

**Comment by marzwick** [comment]
549eec2
