### ISSUE TITLE
use h3 for these headings in intro.md (and others)

### ISSUE THREAD

**Issue by snotskie** [Tiny-Earth/DemoSite#20]
update the following so they use an h3 (`###`) instead of an h2 (`##`)

- https://github.com/Tiny-Earth/DemoSite/blob/4e507465ae84787f1695f3432c9bf4cf18581e18/site/src/intro.md?plain=1#L55
- https://github.com/Tiny-Earth/DemoSite/blob/4e507465ae84787f1695f3432c9bf4cf18581e18/site/src/intro.md?plain=1#L68
- https://github.com/Tiny-Earth/DemoSite/blob/4e507465ae84787f1695f3432c9bf4cf18581e18/site/src/intro.md?plain=1#L97
- https://github.com/Tiny-Earth/DemoSite/blob/4e507465ae84787f1695f3432c9bf4cf18581e18/site/src/intro.md?plain=1#L110
- https://github.com/Tiny-Earth/DemoSite/blob/4e507465ae84787f1695f3432c9bf4cf18581e18/site/src/intro.md?plain=1#L120
- https://github.com/Tiny-Earth/DemoSite/blob/4e507465ae84787f1695f3432c9bf4cf18581e18/site/src/intro.md?plain=1#L290

This is to be consistent with our style that uses h2s after rules (`---`) and h3s for subsections

Also, ensure that other modules follow this same pattern

**Comment by marzwick** [comment]
3750f51
