### ISSUE TITLE
Update module order

### ISSUE THREAD

**Issue by snotskie** [Tiny-Earth/DemoSite#22]
Edit `toc.yaml` here: https://github.com/Tiny-Earth/DemoSite/blob/23c20618d49beac6786f9b1a4d3995c9239c1056/site/toc.yaml#L2-L13

Update the module order to be:

**Part One**

1. Scientific Teaching
2. Inclusive Learning
3. How Learning Works

**Part Two**

1. Course Design
2. Active Learning Experiences
3. Summative Assessment
4. Course Structure

**Part Three**

1. Scientific Teaching Revisited

**Comment by marzwick** [comment]
ab44668

**Comment by snotskie** [comment]
toc does not match the order SM requested

**Comment by marzwick** [comment]
b10d470
