### ISSUE TITLE
Add estimated time to complete on all modules

### ISSUE THREAD

**Issue by snotskie** [Tiny-Earth/DemoSite#6]
For example: https://github.com/Tiny-Earth/DemoSite/blob/4e507465ae84787f1695f3432c9bf4cf18581e18/site/src/design.md?plain=1#L3

Raw times are documented in the Drive files, on comments at the top left by me

Raw times there were calculated by:

$W / 200 * 3$

Where $W$ is the word count according to Docs

Round $W$ to nearest multiple of 5

**Comment by marzwick** [comment]
2cc2ebc
